# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
#relative_permalinks: true

# Setup
title:            Meredith (Wenjun) Wu
baseurl:          https://meredith-wenjunwu.github.io

author:
  name:           'Meredith(Wenjun) Wu'
  # url:            https://meredith-wenjunwu.github.io

paginate:         5


